name: DeePMD-kit

on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'extra info for this github action'
        required: false
        default: 'manually triggered'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_container_and_push:
    runs-on: self-hosted
    
    steps:
      - name: Add Permission
        run: sudo chmod 777 -R ~/actions-runner

      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images:
            registry.dp.tech/flow/deepmd-kit

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
