name: release_docker

on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'extra info for this github action'
        required: false
        default: 'manually triggered'
  push:
    tags:
      - '*'

jobs:
  build_container_and_push:
    runs-on: self-hosted
    
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images:
            registry.dp.tech/flow/deepmd-kit

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Aliyun Registry
        uses: docker/login-action@v1
        with:
          registry: registry.dp.tech
          username: dplc@dptech
          password: ${{ secrets.DPLC_PASSWORD }}

      - name: Build and Push Private Container
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          file: Dockerfile
          push: true
          labels: ${{ steps.meta.outputs.labels }}

      - name: send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.feishu.cn
          server_port: 465
          username: ${{ secrets.CJH_MAILUSERNAME }}
          password: ${{ secrets.CJH_MAILPASSWORD }}
          subject: Auto Build For deepmd-kit docker images with commit:${{ github.event.head_commit.message }}
          body: Image update - ${{ secrets.DPLC_REGISTRY }}/flow/deepmd-kit:${{ steps.meta.outputs.tags }}
          to: ${{ secrets.FEP_MAIL_LIST }}
          from: GitHub Actions
          content_type: text
